### ISSUE TITLE
Can you give a specific instruction on the README file?

### ISSUE THREAD

**Issue by dongzhenye** [scotch-io/All-Github-Emoji-Icons#1]
Hello scotch-io team,

First of all thanks for the project. It's a useful tool for using emoji. However, I am confused about how to quickly use the project.

It is best if [the project home page](https://github.com/scotch-io/All-Github-Emoji-Icons/) shows every icon according to the emoji. But **it shows the same icon** on my latest Chrome browser, and there is a screen shot below:

![screenclip](https://cloud.githubusercontent.com/assets/5765843/5996683/3671a8c6-aae9-11e4-9167-92f612a7512f.png)

Please tell me whether it is a bug, or I didn't get the correct method to use the project. Thanks ahead :bouquet:

**Comment by robertwhitebit** [comment]
@4wheels 
It seems to be a bug on github. If a file is empty, then the latest commit message will be chosen for the middle column.

@scotch-io
I quickly created a shell script which would fix this issue.

```
find * -not -path 'README.md' -exec sh -c "echo ':{}:' > {}; git add {}; git commit -m ':{}:'; " \;
```

This writes the github emoji icon text to the file, adds it and creates a commit with the emoji itself. Then the files aren't empty and the emoji previews are displayed correctly.
See https://github.com/robertwhitebit/All-Github-Emoji-Icons/tree/fixIconPreview for the result.

(btw: I also hard reset the branch to the first commit (`git reset --hard f6eaf6d`) before executing the command and added all empty files. Just for a clean history :wink:)

Since there are pages linking to your repository, I would appreciate it if you fix that.

**Comment by whatnickcodes** [comment]
Can you send a pull request?

**Comment by robertwhitebit** [comment]
@ncerminara 
I can send a pull request without a clean history (a clean history needs a force push :scream_cat:). Which means that ~886 commits will be added to the current master. If you are fine with that, I'll do it asap.

**Comment by robertwhitebit** [comment]
Btw: I would also get rid of the README.md file.
The title and the description on the top of the page have the same content and also the list would be cleaner and would look more like a table. Because if there is no README.md file, there wouldn't be a line in the file list which has the commit message 'Initial commit' (no icon). You see the line I'm talking about in the image in the issue description already.

**Comment by whatnickcodes** [comment]
Great stuff!
